### ISSUE TITLE
qabs per m^2 per hour to high

### ISSUE THREAD

**Issue by EwaGomez** [SunPower/pvfactors#100]
Hi there,
Thanks a lot for making pvfactors free available!
I am currently using it for my master thesis, calculating the effect of the albedo of red soil on the performance of bifacial modules in Ghana.
I am doing a full year simulation and somehow my qabs values are to high. For example
Simulation with 35 degree tilt angle, fixed axis, albedo: 0,3:
Yearly Energy Output : 1742kWh/m2
Max. qabs front: 1410 kWh/m2 (22. of April, 12:00h)

The radiation on this day is:
Global: 967W/m2
Direct: 747 W/m2
Diffuse: 225W/m2
--> the concluding qabs on front don't make any sense, because its to high.

I am lost in finding the error, have you ever experienced something similar?

Best wishes,
Eva

**Comment by anomam** [comment]
Hello @EwaGomez , 

Happy New Year and sorry for the delayed response! I was traveling without much access to the internet.
This sounds like a very interesting project, I actually just got back from West Africa and I'm very happy to read that there's some PV performance research going on there.

There are a number of things that can cause discrepancies between measured and calculated irradiance, and your message is a great reminder that I should create at least a wiki page about what to look at when troubleshooting simulations with ``pvfactors``. Some of the big axes I can think of right now are:
- checking the input data: 
-- it's important to make sure that the irradiance and solar angles measurements are aligned: typically on a clear day, GHI is the highest when the sun is the highest in the sky (minimum zenith). So it would be good to check that.
-- you can also check that the irradiance data is good: are the direct and diffuse values measured correctly? Does the relation ``GHI = DNI * cos(Zenith) + DHI`` hold?
-- another thing to check is the array configuration parameters: a good way to check it in pvfactors is to plot the PV array geometry at a given timestamp, and see if the shadows and the array tilt makes sense. A common mistake for instance is to use an incorrect ``axis azimuth`` angle.
- checking the output data:
-- a good way to make sure the model is used correctly is to compare the calculated ``qabs front`` to what the [Perez model](https://pvlib-python.readthedocs.io/en/stable/generated/pvlib.irradiance.perez.html) as implemented in ``pvlib`` calculates: and if you don't have a lot of direct shading (inter-row) in your PV array, the values should be relatively close between the two models. If they are not, that could be an indication that ``pvfactors`` is not used correctly. If they are close, then ``pvfactors`` is probably used correctly, and then more digging is necessary... (see below)

You may find this [pvfactors benchmark](https://www.researchgate.net/profile/Chetan_Chaudhari10/publication/334432633_A_Benchmark_and_Validation_of_Bifacial_PV_Irradiance_Models/links/5d29166d92851cf4407e801c/A-Benchmark-and-Validation-of-Bifacial-PV-Irradiance-Models.pdf) and this [CEA study](http://bifipv-workshop.com/fileadmin/layout/images/bifiPV/presentations2019/bifiPV2019-CEA_INES_Capelle.pdf) useful as well. It shows how racking can have a significant impact on backside irradiance values, and that 2D models like ``pvfactors`` are currently not designed to account for it and can therefore calculate very different results than what's measured.

Can you share some charts showing both measured and calculated irradiance for your site for a couple of days (eg a clear day and a cloudy day)? Maybe with some of the input data you're using?

**Comment by EwaGomez** [comment]
Thank you for your detailed reply! 

I checked all the above mentioned issues. 

I am starting to think, that the issue is connected to the report I built:
def Segments_report(pvarray):
    
```
    result = {}
    
    for i in range(0, len(pvarray.ts_pvrows)):
        
        row = pvarray.ts_pvrows[i]
        
        result["row_" + str(i) + "_qabs_front"] = row.front.get_param_weighted('qabs').tolist() #total qabs for every row front
        result["row_" + str(i) + "_qabs_back"] = row.back.get_param_weighted('qabs').tolist() #total qabs for every row back
        result["row_" + str(i) + "_qinc_front"] = row.front.get_param_weighted('qinc').tolist() #total qinc for every row front
        result["row_" + str(i) + "_qinc_back"] = row.back.get_param_weighted('qinc').tolist() #total qinc for every row back
        
        for ts_surface in row.front.all_ts_surfaces:
            key = "segment_" + str(ts_surface.index)
            result[key] = ts_surface.get_param('qabs').tolist()
            
        for ts_surface in row.back.all_ts_surfaces:
            key = "segment_" + str(ts_surface.index)
            result[key] = ts_surface.get_param('qabs').tolist()
            
        for ts_surface in row.front.all_ts_surfaces:
            key = "segment_" + str(ts_surface.index)
            result[key] = ts_surface.get_param('qinc').tolist()
            
        for ts_surface in row.back.all_ts_surfaces:
            key = "segment_" + str(ts_surface.index)
            result[key] = ts_surface.get_param('qinc').tolist()
    
    return result
```
I tried to built a report, which exports also the qabs for every segment seperatly, to investigate the differences. Maybe the error is somewhere there? 
The calculated energy over the year in kWh/m2 seems logical, only the qabs in every hour is to high. 

Thank you for all the advice. It is my first attempt with simulating with python.

Best wishes from Cologne!

**Comment by anomam** [comment]
Hi @EwaGomez ,

I may have spotted a typo in your code; I think you're using the same dictionary key names for the segments ``qinc`` and ``qabs`` values. 

I would probably update it to something like the following:

```
def Segments_report(pvarray):
    result = {}
    
    for i in range(0, len(pvarray.ts_pvrows)):
        
        row = pvarray.ts_pvrows[i]
        
        result["row_" + str(i) + "_qabs_front"] = row.front.get_param_weighted('qabs').tolist() #total qabs for every row front
        result["row_" + str(i) + "_qabs_back"] = row.back.get_param_weighted('qabs').tolist() #total qabs for every row back
        result["row_" + str(i) + "_qinc_front"] = row.front.get_param_weighted('qinc').tolist() #total qinc for every row front
        result["row_" + str(i) + "_qinc_back"] = row.back.get_param_weighted('qinc').tolist() #total qinc for every row back
        
        for ts_surface in row.front.all_ts_surfaces:
            key = "qabs_segment_" + str(ts_surface.index)  # updated
            result[key] = ts_surface.get_param('qabs').tolist()
            
        for ts_surface in row.back.all_ts_surfaces:
            key = "qabs_segment_" + str(ts_surface.index)  # updated
            result[key] = ts_surface.get_param('qabs').tolist()
            
        for ts_surface in row.front.all_ts_surfaces:
            key = "qinc_segment_" + str(ts_surface.index)  # updated
            result[key] = ts_surface.get_param('qinc').tolist()
            
        for ts_surface in row.back.all_ts_surfaces:
            key = "qinc_segment_" + str(ts_surface.index)  # udpated
            result[key] = ts_surface.get_param('qinc').tolist()
    
    return result
```

Let me know if that helps!

**Comment by EwaGomez** [comment]
Hi Marc,

Thanks a lot for checking my code. 
Unfortunatly I am still getting the same qabs results. 
I also verified using another set of input weather data, but the front radiation value is still to high to make sense.
