### ISSUE TITLE
How to recover index of segment

### ISSUE THREAD

**Issue by tcapelle** [SunPower/pvfactors#101]
TL;DR: How do I recover the corresponding backface irradiance to compare to my reference cell.

Hello,
I am trying to recover the backface irradiances with the new API.
Probably i am just missing something, but I can't find a way to quickly recover the indexes.
I am doing this:
```
def individual_report(pvarray:OrderedPVArray, row:int=0): 
    back_surface_list = pvarray.ts_pvrows[row].back.list_segments
    return pd.DataFrame({f'qinc_{s.index}':s.get_param_weighted('qinc') for s in back_surface_list})
```
but the `s.index` is always none.
If I index using `all_ts_surfaces` I get way too much segments. I know that al surfaces are listed, including shaded elements.
Any tips?

**Comment by tcapelle** [comment]
Ok, 
There are `TsSegment` and `TsSurface`, but the indexes I plotted only show surface, but not segments.
This is pretty confusing btw...

**Comment by anomam** [comment]
Hey @tcapelle , thanks a lot for flagging this! Sorry I haven't been very active on pvfactors lately, I'm a bit buried at work
- It does seem like the segments' ``index`` attribute is never set, good catch! It should be an easy fix, just changing [this line](https://github.com/SunPower/pvfactors/blob/422f883fd6e68c38900ceb74977b3267555f3fee/pvfactors/geometry/pvrow.py#L340-L341) to:
```
segment = TsSegment(segment_coords, illum, shaded,
                                n_vector=n_vector, index=i)
```
I'll try to do it this week, but feel free to open a PR if you can!
- In the meantime for your situation, you could just use the segment's index in the list of segments for now (it's exactly what's going to be used after the fix):
```
def individual_report(pvarray:OrderedPVArray, row:int=0): 
    back_surface_list = pvarray.ts_pvrows[row].back.list_segments
    return pd.DataFrame({f'qinc_{idx}':s.get_param_weighted('qinc') for idx, s in enumerate(back_surface_list)})
```
- I'd be more than happy to help here; could you just clarify what you find confusing and what solution you think could help?
>Ok,
There are TsSegment and TsSurface, but the indexes I plotted only show surface, but not segments.
This is pretty confusing btw...

Thanks a lot for opening this issue!
