### ISSUE TITLE
Implement Backtracking Algorithm

### ISSUE THREAD

**Issue by btaute** [SunPower/pvfactors#104]
It's possible that the package already incorporates a backtracking algorithm, but I cannot find documentation stating so.  If not, could this be a feature that gets implemented?

**Comment by anomam** [comment]
Hi @btaute , thanks a lot for giving pvfactors a try!
pvfactors does not implement any tracking algorithm to give the users the freedom to use any tracking angles they wish for their systems by passing it as input to the ``PVEngine.fit()`` method.
There are awesome libraries like [pvlib-python](https://github.com/pvlib/pvlib-python) that provide user-friendly and well-documented functions for classical [tracking algorithms](https://pvlib-python.readthedocs.io/en/stable/api.html#tracking), including backtracking. You can find an example of how I use the ``singleaxis()`` method in this [study](https://github.com/anomam/pvfactors_iea_pvps_study/blob/master/data_preprocessing.ipynb) for instance.
Let me know if this helps!

**Comment by btaute** [comment]
Thanks for the clarification!
