### ISSUE TITLE
Could not find module

### ISSUE THREAD

**Issue by jf9810** [SunPower/pvfactors#106]
I am using pvlib.bifacial.pvfactors_timeseries,  but when i run it i get this error

pvlib.bifacial.pvfactors_timeseries(solar_azimuth=PosSol['azimuth'], 
                                    solar_zenith=PosSol['zenith'], 
                                    surface_azimuth=surface_azimuth, 
                                    surface_tilt=surface_tilt, 
                                    axis_azimuth=0.0,
                                    timestamps=data_weatherforecast.index, 
                                    dni=data_weatherforecast['dni'], 
                                    dhi=data_weatherforecast['dhi'], 
                                    gcr=0.716, 
                                    pvrow_height=1, 
                                    pvrow_width=2, 
                                    albedo=albedo, 
                                    n_pvrows=3, 
                                    index_observed_pvrow=1, 
                                    rho_front_pvrow=0.03, 
                                    rho_back_pvrow=0.05, 
                                    horizon_band_angle=15.0)

But when i run it i get this error:

Could not find module 'C:\anaconda\Library\bin\geos_c.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by anomam** [comment]
hi @jf9810 , it looks like you're missing a shapely dependency (GEOS) that pvfactors requires at the moment (there are plans to remove it in the future). For now, could you try uninstalling ``shapely`` and re-installing it using the wheel files from this [website](https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely)?

**Comment by anomam** [comment]
hi @jf9810 , I'm going to close this issue because of inactivity. But feel free to re-open it if you have any additional questions.
