### ISSUE TITLE
Feature Request: raise a more informative message when geos_c.dll isn't found

### ISSUE THREAD

**Issue by kanderso-nrel** [SunPower/pvfactors#109]
Installing shapely from pip instead of conda is a frequent roadblock for users that haven't been exposed to binary python dependencies:
- https://github.com/SunPower/pvfactors/issues/106
- https://groups.google.com/g/pvlib-python/c/0WM8Soc8PiQ
- https://stackoverflow.com/questions/65790878/error-winerror-126-the-specified-module-could-not-be-found
- https://stackoverflow.com/questions/64671004/could-not-find-module-pvfactors
- https://stackoverflow.com/questions/64037211/oserror-winerror-126-the-specified-module-could-not-be-found-using-pvfactor

I see in https://github.com/SunPower/pvfactors/issues/106 that the shapely dependency is planned to be dropped in the future -- will that be happening in the near future?  If it might be a while, what do you think about wrapping shapely imports in a try/except and raising a new error with a helpful hint about installing shapely from conda instead of pip?  If that sounds like a good idea, I'm happy to open a PR -- it might be as simple as just adding something like this at the top of `__init__.py`, or it might need it everywhere shapely is imported, not sure:

```python
try:
    import shapely
except OSError:
    # can't use "raise from" here because py2.7 doesn't support it.  Or drop 2.7 support, see #107
    raise ImportError("Something helpful about conda vs pip for shapely") 
```

**Comment by anomam** [comment]
@kanderso-nrel thanks so much for your message and for tracking all these user issues, I had no idea it was such a big problem for people. Unfortunately I don't have any time to work on dropping the shapely dependency, but I do very much welcome any contributions that can make things easier for users. So please feel free to open a PR and I will happily review it!

Something in the top `__init__.py` file would be good enough for me.
