### ISSUE TITLE
PyPI project authorization

### ISSUE THREAD

**Issue by campanelli-sunpower** [SunPower/pvfactors#137]
@anomam I have tagged `pvfactors` at v1.5.2. However, I cannot upload to PyPI using twine because the `pvfactors` project is not associated with my username `campanelli-sunpower`. Do I need you to add me in PyPI, or perhaps I ask SunPower IT for this? Please advise. Thanks.

Also, would you provide a name for this release? (I do not know Japanese :).) It's currently a pre-release named TBD at https://github.com/SunPower/pvfactors/releases/tag/v1.5.2.

**Comment by kanderso-nrel** [comment]
Thanks @campanelli-sunpower! One other thing for the 1.5.2 release is to fill in the release date here: https://sunpower.github.io/pvfactors/whatsnew.html

**Comment by anomam** [comment]
@campanelli-sunpower 
😄 it doesn't have to be anything Japanese, you can choose whatever you want. If you have no inspiration I guess we could go with "Fujisan Reiwa Renkon" : )
For pypi I can see that the SunPower PyPi account ("perfspwr") still has maintainer access to the pvfactors project; and it's the same account used for all the other SunPower open-source projects including PVMismatch, so it would probably be useful for you to find the credentials for it. Let me know if you're not able to find it and I'll just add your account if you have one already.

<img width="1160" alt="image" src="https://user-images.githubusercontent.com/12040910/155318308-4066b6e8-b905-4ef4-bf5c-7be15e061a0d.png">

**Comment by campanelli-sunpower** [comment]
I made a request to SunPower for access to the `perfspwr` account.

**Comment by campanelli-sunpower** [comment]
@anomam SunPower has no record of the `perfspwr` account. I don't think you can reset that, so we may need to add me first (campanelli-sunpower), then I can create a more proper new SunPower-level account with access.

**Comment by anomam** [comment]
@campanelli-sunpower ok thanks for checking, that's a bit worrisome for all these other open-source packages though 😅 I know that @chetan201 was maintaining PVMismatch before leaving so maybe he has an idea, did you try asking @GregoryKimball ? He may have taken over the project and account.. 🤷

**Comment by campanelli-sunpower** [comment]
Thanks @anomam. Looks like @GregoryKimball is also no longer with SunPower.

Please know that I do care about the present and future of these open source projects, but we are bandwidth limited ATM.

**Comment by anomam** [comment]
> I do care about the present and future of these open source projects

and I greatly appreciate it!! 🙏 I just added you to the pypi project : )

**Comment by campanelli-sunpower** [comment]
v1.5.2 has been pushed to PyPI. (cc @kanderso-nrel for consumption in pvlib). Closing this issue.
