### ISSUE TITLE
Implement AOI losses method

### ISSUE THREAD

**Issue by anomam** [SunPower/pvfactors#36]
Should be implemented with the new pvfactors API

**Comment by tcapelle** [comment]
Could not we use just use the PVLib AOI losses computations?

**Comment by anomam** [comment]
Thanks for the comment @tcapelle 
I could be wrong, but I believe pvlib can only calculate the AOI losses for the direct component of the incident light. Here we would need to calculate a value for each view factor of a surface to another... (or maybe just the ones of interest, maybe multiple approaches should be tested).
Thankfully it should be relatively easy to test multiple approaches using the new package API
