### ISSUE TITLE
Update Python 3 version support

### ISSUE THREAD

**Issue by markcampanelli** [SunPower/pvfactors#49]
https://github.com/pvlib/pvlib-python/tree/v0.6.3 lists Python 3.4-7 support (see https://github.com/pvlib/pvlib-python/blob/v0.6.3/setup.py). `pvfactors` is listed as optional, but is called out in the CI requirements for the Python 3.5-7 runs, but Python 3.4 is not included (e.g., https://github.com/pvlib/pvlib-python/blob/v0.6.3/ci/requirements-py34.yml vs. https://github.com/pvlib/pvlib-python/blob/v0.6.3/ci/requirements-py37.yml).

`pvfactors` should be more clear about which Python 3 versions are supported in the `CLASSIFIERS` variable in https://github.com/SunPower/pvfactors/blob/master/setup.py (e.g., more than just 'Programming Language :: Python :: 3.6'). It would also be worth checking that the dependency ranges in https://github.com/SunPower/pvfactors/blob/master/requirements.txt are indeed compatible with those Python 3 versions. (It might be nice to be more specific about Python 2 versions as well.)

**Comment by markcampanelli** [comment]
@anomam Do you know what the lower bound on `pandas` should now be?

https://github.com/SunPower/pvfactors/blob/master/requirements.txt#L3

**Comment by anomam** [comment]
Thanks for this @markcampanelli , I think that the lower bound should be the same as in pvlib, because the only functions in pvfactors that really depend on pandas are in the irradiance models, which use pvlib. I'm thinking of just removing the lower bound on that line (and maybe a few other lines as well)
